# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [16]:
# Import reduce from functools, numpy and pandas
from functools import reduce
import numpy as np


ModuleNotFoundError: No module named 'panda'

In [30]:


a = np.random.random((10,4))
print(a)

b = np.random.random((5,2,3))
print(b)

[[0.28938342 0.30539279 0.07487364 0.08001658]
 [0.25885127 0.46506009 0.6602645  0.42862764]
 [0.59928711 0.69000984 0.76860141 0.28829014]
 [0.9428143  0.08824394 0.45412583 0.5301913 ]
 [0.428513   0.21249166 0.86121723 0.53851495]
 [0.8636068  0.93684282 0.89015416 0.58762734]
 [0.13133249 0.59832354 0.57900747 0.75927371]
 [0.76212826 0.13362528 0.01456879 0.98359169]
 [0.23288877 0.90679594 0.85635967 0.75977282]
 [0.74562823 0.24981608 0.76724605 0.97812824]]
[[[0.53550637 0.21054246 0.54002934]
  [0.75779865 0.83517887 0.53475646]]

 [[0.0083385  0.67182843 0.01426439]
  [0.23446394 0.56220872 0.37419717]]

 [[0.13160433 0.14245488 0.0627104 ]
  [0.44933322 0.21206053 0.02341781]]

 [[0.69608707 0.30998064 0.75208757]
  [0.19017537 0.6545282  0.42876538]]

 [[0.49104441 0.00305514 0.98418051]
  [0.61315699 0.79470347 0.21121168]]]


In [10]:
area_triangulo = lambda base,altura: (base * altura) / 2

print (area_triangulo (5,10))
print (area_triangulo (10,15))


## FUNCIÓN MAP ##
def half(x):
    return x / 2
l = [10, 12, 34, 23]
x = list(map(half, l))
print (x)


25.0
75.0
[5.0, 6.0, 17.0, 11.5]


# Challenge 1 - Mapping

#### We will use the map function to clean up words in a book.

In the following cell, we will read a text file containing the book The Prophet by Khalil Gibran.

In [38]:
# Run this code:

location = "/Users/antoniohuerta/IronHack/dataptmad1121_labs/module-1/map-reduce-filter/data58585-0.txt"


with open(location, 'r', encoding="utf8") as f:
    prophet = f.read().split(' ')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/antoniohuerta/IronHack/dataptmad1121_labs/module-1/map-reduce-filter/data58585-0.txt'

#### Let's remove the first 568 words since they contain information about the book but are not part of the book itself. 

Do this by removing from `prophet` elements 0 through 567 of the list (you can also do this by keeping elements 568 through the last element).

In [7]:
# your code here

print (location)


../data/58585-0.txt


If you look through the words, you will find that many words have a reference attached to them. For example, let's look at words 1 through 10.

In [ ]:
# your code here

#### The next step is to create a function that will remove references. 

We will do this by splitting the string on the `{` character and keeping only the part before this character. Write your function below.

In [ ]:
def reference(x):
    '''
    Input: A string
    Output: The string with references removed
    
    Example:
    Input: 'the{7}'
    Output: 'the'
    '''
    
    # your code here

Now that we have our function, use the `map()` function to apply this function to our book, The Prophet. Return the resulting list to a new list called `prophet_reference`.

In [ ]:
# your code here

Another thing you may have noticed is that some words contain a line break. Let's write a function to split those words. Our function will return the string split on the character `\n`. Write your function in the cell below.

In [ ]:
def line_break(x):
    '''
    Input: A string
    Output: A list of strings split on the line break (\n) character
        
    Example:
    Input: 'the\nbeloved'
    Output: ['the', 'beloved']
    '''
    
    # your code here

Apply the `line_break` function to the `prophet_reference` list. Name the new list `prophet_line`.

In [ ]:
# your code here

If you look at the elements of `prophet_line`, you will see that the function returned lists and not strings. Our list is now a list of lists. Flatten the list using list comprehension. Assign this new list to `prophet_flat`.

In [ ]:
# your code here

# Challenge 2 - Filtering

When printing out a few words from the book, we see that there are words that we may not want to keep if we choose to analyze the corpus of text. Below is a list of words that we would like to get rid of. Create a function that will return false if it contains a word from the list of words specified and true otherwise.

In [ ]:
def word_filter(x):
    '''
    Input: A string
    Output: True if the word is not in the specified list 
    and False if the word is in the list.
        
    Example:
    word list = ['and', 'the']
    Input: 'and'
    Output: False
    
    Input: 'John'
    Output: True
    '''
    
    word_list = ['and', 'the', 'a', 'an']
    
    # your code here

Use the `filter()` function to filter out the words speficied in the `word_filter()` function. Store the filtered list in the variable `prophet_filter`.

# Bonus Challenge

Rewrite the `word_filter` function above to not be case sensitive.

In [ ]:
def word_filter_case(x):
   
    word_list = ['and', 'the', 'a', 'an']
    
    # your code here

# Challenge 3 - Reducing

#### Now that we have significantly cleaned up our text corpus, let's use the `reduce()` function to put the words back together into one long string separated by spaces. 

We will start by writing a function that takes two strings and concatenates them together with a space between the two strings.

In [ ]:
def concat_space(a, b):
    '''
    Input:Two strings
    Output: A single string separated by a space
        
    Example:
    Input: 'John', 'Smith'
    Output: 'John Smith'
    '''
    
    # your code here

Use the function above to reduce the text corpus in the list `prophet_filter` into a single string. Assign this new string to the variable `prophet_string`.

In [ ]:
# your code here

# Challenge 4 - Applying Functions to DataFrames

#### Our next step is to use the apply function to a dataframe and transform all cells.

To do this, we will connect to Ironhack's database and retrieve the data from the *pollution* database. Select the *beijing_pollution* table and retrieve its data.

In [ ]:
# your code here

Let's look at the data using the `head()` function.

In [ ]:
# your code here

The next step is to create a function that divides a cell by 24 to produce an hourly figure. Write the function below.

In [ ]:
def hourly(x):
    '''
    Input: A numerical value
    Output: The value divided by 24
        
    Example:
    Input: 48
    Output: 2.0
    '''
    
    # your code here

Apply this function to the columns `Iws`, `Is`, and `Ir`. Store this new dataframe in the variable `pm25_hourly`.

In [ ]:
# your code here

#### Our last challenge will be to create an aggregate function and apply it to a select group of columns in our dataframe.

Write a function that returns the standard deviation of a column divided by the length of a column minus 1. Since we are using pandas, do not use the `len()` function. One alternative is to use `count()`. Also, use the numpy version of standard deviation.

In [ ]:
def sample_sd(x):
    '''
    Input: A Pandas series of values
    Output: the standard deviation divided by the number of elements in the series
        
    Example:
    Input: pd.Series([1,2,3,4])
    Output: 0.3726779962
    '''
    
    # your code here