# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [16]:
# Import reduce from functools, numpy and pandas
from functools import reduce
import numpy as np


ModuleNotFoundError: No module named 'panda'

In [39]:


a = np.random.random((10,4))
print(a)

b = np.random.random((5,2,3))
print(b)




[[0.17962145 0.43466666 0.6014713  0.63894438]
 [0.23242514 0.1653238  0.19589498 0.0960171 ]
 [0.67118511 0.28816811 0.67820635 0.74486428]
 [0.52160816 0.16792415 0.48692658 0.81173643]
 [0.03010151 0.85601506 0.71262113 0.41023131]
 [0.59192046 0.31840987 0.32122494 0.51265272]
 [0.86184525 0.26976152 0.57571455 0.07123011]
 [0.69554229 0.9789538  0.47106501 0.99127134]
 [0.81101096 0.60715141 0.87450237 0.63167656]
 [0.19399532 0.57105503 0.22379618 0.58095831]]
[[[0.31644172 0.08330986 0.11786712]
  [0.51919031 0.59234383 0.64789965]]

 [[0.26979486 0.6184178  0.57393455]
  [0.82222184 0.24177114 0.32541996]]

 [[0.42453904 0.09607569 0.94984143]
  [0.78335482 0.85325096 0.31854078]]

 [[0.99241033 0.20357163 0.3575633 ]
  [0.50159133 0.86721217 0.81983573]]

 [[0.3663829  0.85587697 0.83635296]
  [0.05468545 0.67273728 0.95597421]]]


In [10]:
area_triangulo = lambda base,altura: (base * altura) / 2

print (area_triangulo (5,10))
print (area_triangulo (10,15))


## FUNCIÓN MAP ##
def half(x):
    return x / 2
l = [10, 12, 34, 23]
x = list(map(half, l))
print (x)


25.0
75.0
[5.0, 6.0, 17.0, 11.5]


In [54]:
#Creamos una matriz como una tupla
list_list = [[i + j for i in range (6)] for j in range(0,60,10)]
print (lis_list)
#Creamos un array con la madrid utilizando nympy
a = np.array(list_list)

# Tomo la primera columna de la matriz
print(a[:,0])

## Imprimir un elemento concreto de la matiz (Cuarta fila, segunda columna)
print(a[4,2])

## Imprimir la segunda fila)
print(a[2,:])

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]
[ 0 10 20 30 40 50]
42
[20 21 22 23 24 25]


# Challenge 1 - Mapping

#### We will use the map function to clean up words in a book.

In the following cell, we will read a text file containing the book The Prophet by Khalil Gibran.

In [38]:
# Run this code:

location = "/Users/antoniohuerta/IronHack/dataptmad1121_labs/module-1/map-reduce-filter/data58585-0.txt"


with open(location, 'r', encoding="utf8") as f:
    prophet = f.read().split(' ')

FileNotFoundError: [Errno 2] No such file or directory: '/Users/antoniohuerta/IronHack/dataptmad1121_labs/module-1/map-reduce-filter/data58585-0.txt'

#### Let's remove the first 568 words since they contain information about the book but are not part of the book itself. 

Do this by removing from `prophet` elements 0 through 567 of the list (you can also do this by keeping elements 568 through the last element).

In [7]:
# your code here

print (location)


../data/58585-0.txt


If you look through the words, you will find that many words have a reference attached to them. For example, let's look at words 1 through 10.

In [ ]:
# your code here

#### The next step is to create a function that will remove references. 

We will do this by splitting the string on the `{` character and keeping only the part before this character. Write your function below.

In [ ]:
def reference(x):
    '''
    Input: A string
    Output: The string with references removed
    
    Example:
    Input: 'the{7}'
    Output: 'the'
    '''
    
    # your code here

Now that we have our function, use the `map()` function to apply this function to our book, The Prophet. Return the resulting list to a new list called `prophet_reference`.

In [ ]:
# your code here

Another thing you may have noticed is that some words contain a line break. Let's write a function to split those words. Our function will return the string split on the character `\n`. Write your function in the cell below.

In [ ]:
def line_break(x):
    '''
    Input: A string
    Output: A list of strings split on the line break (\n) character
        
    Example:
    Input: 'the\nbeloved'
    Output: ['the', 'beloved']
    '''
    
    # your code here

Apply the `line_break` function to the `prophet_reference` list. Name the new list `prophet_line`.

In [ ]:
# your code here

If you look at the elements of `prophet_line`, you will see that the function returned lists and not strings. Our list is now a list of lists. Flatten the list using list comprehension. Assign this new list to `prophet_flat`.

In [ ]:
# your code here

# Challenge 2 - Filtering

When printing out a few words from the book, we see that there are words that we may not want to keep if we choose to analyze the corpus of text. Below is a list of words that we would like to get rid of. Create a function that will return false if it contains a word from the list of words specified and true otherwise.

In [ ]:
def word_filter(x):
    '''
    Input: A string
    Output: True if the word is not in the specified list 
    and False if the word is in the list.
        
    Example:
    word list = ['and', 'the']
    Input: 'and'
    Output: False
    
    Input: 'John'
    Output: True
    '''
    
    word_list = ['and', 'the', 'a', 'an']
    
    # your code here

Use the `filter()` function to filter out the words speficied in the `word_filter()` function. Store the filtered list in the variable `prophet_filter`.

# Bonus Challenge

Rewrite the `word_filter` function above to not be case sensitive.

In [ ]:
def word_filter_case(x):
   
    word_list = ['and', 'the', 'a', 'an']
    
    # your code here

# Challenge 3 - Reducing

#### Now that we have significantly cleaned up our text corpus, let's use the `reduce()` function to put the words back together into one long string separated by spaces. 

We will start by writing a function that takes two strings and concatenates them together with a space between the two strings.

In [ ]:
def concat_space(a, b):
    '''
    Input:Two strings
    Output: A single string separated by a space
        
    Example:
    Input: 'John', 'Smith'
    Output: 'John Smith'
    '''
    
    # your code here

Use the function above to reduce the text corpus in the list `prophet_filter` into a single string. Assign this new string to the variable `prophet_string`.

In [ ]:
# your code here

# Challenge 4 - Applying Functions to DataFrames

#### Our next step is to use the apply function to a dataframe and transform all cells.

To do this, we will connect to Ironhack's database and retrieve the data from the *pollution* database. Select the *beijing_pollution* table and retrieve its data.

In [ ]:
# your code here

Let's look at the data using the `head()` function.

In [ ]:
# your code here

The next step is to create a function that divides a cell by 24 to produce an hourly figure. Write the function below.

In [ ]:
def hourly(x):
    '''
    Input: A numerical value
    Output: The value divided by 24
        
    Example:
    Input: 48
    Output: 2.0
    '''
    
    # your code here

Apply this function to the columns `Iws`, `Is`, and `Ir`. Store this new dataframe in the variable `pm25_hourly`.

In [ ]:
# your code here

#### Our last challenge will be to create an aggregate function and apply it to a select group of columns in our dataframe.

Write a function that returns the standard deviation of a column divided by the length of a column minus 1. Since we are using pandas, do not use the `len()` function. One alternative is to use `count()`. Also, use the numpy version of standard deviation.

In [ ]:
def sample_sd(x):
    '''
    Input: A Pandas series of values
    Output: the standard deviation divided by the number of elements in the series
        
    Example:
    Input: pd.Series([1,2,3,4])
    Output: 0.3726779962
    '''
    
    # your code here