# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import pandas as pd
import numpy as np



#### 2. Print your NumPy version.

In [2]:
# your code here

print(np.__version__)

1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
b = np.random.rand(2,3,5)

In [4]:
print (b)

[[[0.87775618 0.60783713 0.80951537 0.8825994  0.92796479]
  [0.38733498 0.87223009 0.1522443  0.03770452 0.35755346]
  [0.53586371 0.28496474 0.36178229 0.66801565 0.73326292]]

 [[0.22298679 0.79747002 0.02873735 0.46488112 0.35134429]
  [0.36088664 0.51374901 0.69475643 0.79034301 0.15443594]
  [0.82207712 0.58613615 0.98520122 0.70818319 0.38211855]]]


In [5]:
# Method 2

d0_array = np.zeros((2,3,5)) 
print (d0_array)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [6]:
d1_array = np.ones((2,3,5)) 
print (d1_array)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [7]:
# Method 3
d3_array = np.random.randint(0, 100, size=(2, 3, 5))
a = (d3_array)

#### 4. Print *a*.


In [8]:
# your code here
print (a)

[[[20 97 96 32 97]
  [31 86 45 84 37]
  [20 26 94 70 61]]

 [[94 77 43 99 70]
  [38 87 20 16 32]
  [10 93 42  7 61]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
# your code here
b = np.ones((5,2,3)) 

#### 6. Print *b*.


In [10]:
# your code here
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
# your code here
def size_array (a,b):

    if a.size == b.size:
        print (True)
    else:
        print (False)


In [12]:
size_array (a,b)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [13]:
# your answer here
c= a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [14]:
# No me deja unirlos porque no tienen la misma forma

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [15]:
# your code here
c = b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [16]:
# your code/answer here
d = a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [17]:
# your code/answer here
print (a)
print (d)

[[[20 97 96 32 97]
  [31 86 45 84 37]
  [20 26 94 70 61]]

 [[94 77 43 99 70]
  [38 87 20 16 32]
  [10 93 42  7 61]]]
[[[ 21.  98.  97.  33.  98.]
  [ 32.  87.  46.  85.  38.]
  [ 21.  27.  95.  71.  62.]]

 [[ 95.  78.  44. 100.  71.]
  [ 39.  88.  21.  17.  33.]
  [ 11.  94.  43.   8.  62.]]]


In [18]:
## La estructura es la misma, la diferencia está en el tipo de datos de los elementos (int vs float)


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [19]:
# your code here
e = a*c

In [20]:
print (e)

[[[20. 97. 96. 32. 97.]
  [31. 86. 45. 84. 37.]
  [20. 26. 94. 70. 61.]]

 [[94. 77. 43. 99. 70.]
  [38. 87. 20. 16. 32.]
  [10. 93. 42.  7. 61.]]]


In [21]:
print (a)

[[[20 97 96 32 97]
  [31 86 45 84 37]
  [20 26 94 70 61]]

 [[94 77 43 99 70]
  [38 87 20 16 32]
  [10 93 42  7 61]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [22]:
# your code/answer here
np.array_equiv(e,a)

True

In [23]:
np.allclose(e,a) 

True

In [24]:
## Si, son iguales

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [25]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [26]:
# your code here

f = np.empty((2, 3, 5))

In [27]:
print (f)

[[[20. 97. 96. 32. 97.]
  [31. 86. 45. 84. 37.]
  [20. 26. 94. 70. 61.]]

 [[94. 77. 43. 99. 70.]
  [38. 87. 20. 16. 32.]
  [10. 93. 42.  7. 61.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [28]:
# your code here: Se puede plantear como funciones aisladas. vamos a ver como se aáde un valor en la matriz

f = []
for i in np.nditer(d):
            if i > d_min and i < d_mean:
                f.append(25)
            elif i > d_mean and i < d_max:
                f.append(75)
            elif i == d_mean:
                f.append(50)
            elif i == d_min:
                f.append(0)
            elif i == d_max:
                f.append(100)
f = np.reshape(f, (2,3,5))
print(f)

[[[ 25  75  75  25  75]
  [ 25  75  25  75  25]
  [ 25  25  75  75  75]]

 [[ 75  75  25 100  75]
  [ 25  75  25  25  25]
  [ 25  75  25   0  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [30]:
# your code here
print (d)
print (f)

[[[ 21.  98.  97.  33.  98.]
  [ 32.  87.  46.  85.  38.]
  [ 21.  27.  95.  71.  62.]]

 [[ 95.  78.  44. 100.  71.]
  [ 39.  88.  21.  17.  33.]
  [ 11.  94.  43.   8.  62.]]]
[[[ 25  75  75  25  75]
  [ 25  75  25  75  25]
  [ 25  25  75  75  75]]

 [[ 75  75  25 100  75]
  [ 25  75  25  25  25]
  [ 25  75  25   0  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [32]:
# your code here

e = []
for i in np.nditer(d):
            if i > d_min and i < d_mean:
                e.append("A")
            elif i > d_mean and i < d_max:
                e.append("B")
            elif i == d_mean:
                e.append("C")
            elif i == d_min:
                e.append("D")
            elif i == d_max:
                e.append("E")
e = np.reshape(e, (2,3,5))
print(e)

[[['A' 'B' 'B' 'A' 'B']
  ['A' 'B' 'A' 'B' 'A']
  ['A' 'A' 'B' 'B' 'B']]

 [['B' 'B' 'A' 'E' 'B']
  ['A' 'B' 'A' 'A' 'A']
  ['A' 'B' 'A' 'D' 'B']]]
