# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import pandas as pd
import numpy as np



#### 2. Print your NumPy version.

In [2]:
# your code here

print(np.__version__)

1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
b = np.random.rand(2,3,5)

In [4]:
print (b)

[[[0.40379894 0.74241989 0.17098838 0.0502143  0.96245888]
  [0.18763028 0.86009212 0.25812736 0.48688839 0.49234434]
  [0.86432742 0.51112811 0.30210171 0.15711907 0.44162456]]

 [[0.84636426 0.55066048 0.08471103 0.17514475 0.92206335]
  [0.55108227 0.51033378 0.55890498 0.84628462 0.1209135 ]
  [0.69624474 0.27283609 0.51341387 0.82684524 0.38525848]]]


In [5]:
# Method 2

d0_array = np.zeros((2,3,5)) 
print (d0_array)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [6]:
d1_array = np.ones((2,3,5)) 
print (d1_array)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [7]:
# Method 3
d3_array = np.random.randint(0, 100, size=(2, 3, 5))
a = (d3_array)

#### 4. Print *a*.


In [8]:
# your code here
print (a)

[[[77 93 52 26 90]
  [ 5 91 85 65 84]
  [16 16 88 13 48]]

 [[61 14 75 47  7]
  [65 56 95 62 64]
  [62 56 81 12 38]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
# your code here
b = np.ones((5,2,3)) 

#### 6. Print *b*.


In [10]:
# your code here
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [11]:
# your code here
def size_array (a,b):

    if a.size == b.size:
        print (True)
    else:
        print (False)


In [12]:
size_array (a,b)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [13]:
# your answer here
c= a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
# No me deja unirlos porque no tienen la misma forma

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [14]:
# your code here
c = b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [15]:
# your code/answer here
d = a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [16]:
# your code/answer here
print (a)
print (d)

[[[77 93 52 26 90]
  [ 5 91 85 65 84]
  [16 16 88 13 48]]

 [[61 14 75 47  7]
  [65 56 95 62 64]
  [62 56 81 12 38]]]
[[[78. 94. 53. 27. 91.]
  [ 6. 92. 86. 66. 85.]
  [17. 17. 89. 14. 49.]]

 [[62. 15. 76. 48.  8.]
  [66. 57. 96. 63. 65.]
  [63. 57. 82. 13. 39.]]]


In [17]:
## La estructura es la misma, la diferencia está en el tipo de datos de los elementos (int vs float)


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [18]:
# your code here
e = a*c

In [19]:
print (e)

[[[77. 93. 52. 26. 90.]
  [ 5. 91. 85. 65. 84.]
  [16. 16. 88. 13. 48.]]

 [[61. 14. 75. 47.  7.]
  [65. 56. 95. 62. 64.]
  [62. 56. 81. 12. 38.]]]


In [20]:
print (a)

[[[77 93 52 26 90]
  [ 5 91 85 65 84]
  [16 16 88 13 48]]

 [[61 14 75 47  7]
  [65 56 95 62 64]
  [62 56 81 12 38]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [21]:
# your code/answer here
np.array_equiv(e,a)

True

In [22]:
np.allclose(e,a) 

True

In [23]:
## Si, son iguales

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [24]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [29]:
# your code here

f = np. empty((2, 3, 5))

In [30]:
print (f)

[[[77. 93. 52. 26. 90.]
  [ 5. 91. 85. 65. 84.]
  [16. 16. 88. 13. 48.]]

 [[61. 14. 75. 47.  7.]
  [65. 56. 95. 62. 64.]
  [62. 56. 81. 12. 38.]]]


In [43]:
print(f[0,0,0])
for i in f:
    for n in i:
        # print (n)
        for p in n:
            print (p)
    #print (i)

77.0
77.0
93.0
52.0
26.0
90.0
5.0
91.0
85.0
65.0
84.0
16.0
16.0
88.0
13.0
48.0
61.0
14.0
75.0
47.0
7.0
65.0
56.0
95.0
62.0
64.0
62.0
56.0
81.0
12.0
38.0


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [27]:
# your code here: Se puede plantear como un condicional o funciones aisladas. 

## Para cada valor en d, si es mayor que d_min pero menor que d_mean, asigne 25 al valor correspondiente en f.
for i in f:
    for n in i:
        # print (n)
        for p in n:
            #print (p):  
# Si i es mayor que d_min pero menor que d_mean, asigne 25 al valor correspondiente en f.
            if p > d_min and p < d_mean:
        # asigne 25 al valor correspondiente (a0) en f matriz
    elif:
## Si un valor en d es mayor que d_mean pero menor que d_max, asigne 75 al valor correspondiente en f. 
        p > d_mean and p < d_max:
        # asigne 25 al valor correspondiente (a0) en f matriz
    elif:
## Si un valor es igual a d_mean, asigne 50 al valor correspondiente en f.
        p == d_mean:
        # asigne 50 al valor correspondiente (a0) en f matriz
        

## Asigne 0 a los valores correspondientes en f para d_min en d. Asignar 0 la la casilla 
## correspondiente de f equivalente a la que contiene el valor d_min en su índice 

## Assign 100 to the corresponding value(s) in f for d_max in d. Asignar 0 la la casilla 
## correspondiente de f equivalente a la que contiene el valor d_min en su índice

IndentationError: expected an indented block (3839480324.py, line 8)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here